-- 코드를 입력하세요
SELECT A.AUTHOR_ID, C.AUTHOR_NAME, A.CATEGORY, SUM(B.SALES*A.PRICE) AS TOTAL_SALES
FROM BOOK A INNER JOIN (SELECT BOOK_ID, SALES_DATE, SALES
                       FROM BOOK_SALES
                       WHERE YEAR(SALES_DATE) = 2022
                       AND MONTH(SALES_DATE) = 01) B
ON A.BOOK_ID = B.BOOK_ID
INNER JOIN AUTHOR C
ON A.AUTHOR_ID = C.AUTHOR_ID
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC