SELECT C.AUTHOR_ID, D.AUTHOR_NAME, C.CATEGORY, C.TOTAL_SALES
FROM
(SELECT B.CATEGORY, B.AUTHOR_ID, SUM(A.TOTAL*B.PRICE) AS TOTAL_SALES
FROM
(SELECT BOOK_ID, SUM(SALES) AS TOTAL
FROM BOOK_SALES
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY BOOK_ID) A JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
GROUP BY B.CATEGORY, B.AUTHOR_ID) C JOIN AUTHOR D ON C.AUTHOR_ID = D.AUTHOR_ID
ORDER BY 1, 3 DESC

