SELECT C.AUTHOR_ID, D.AUTHOR_NAME, C.CATEGORY, C.TOTAL_SALES
FROM (
    SELECT B.CATEGORY, B.AUTHOR_ID, SUM(SALES * B.PRICE) AS TOTAL_SALES
    FROM BOOK_SALES A
    JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
    WHERE A.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY B.CATEGORY, B.AUTHOR_ID
) C
JOIN AUTHOR D ON C.AUTHOR_ID = D.AUTHOR_ID
ORDER BY C.AUTHOR_ID, C.CATEGORY DESC;
