-- 코드를 입력하세요
SELECT C1.CART_ID
FROM
(
SELECT DISTINCT CART_ID, NAME
FROM CART_PRODUCTS
GROUP BY CART_ID, NAME
HAVING NAME = 'Milk' OR NAME = 'Yogurt'
) C1
GROUP BY C1.CART_ID
HAVING COUNT(C1.CART_ID) = 2
ORDER BY C1.CART_ID
    