-- 코드를 작성해주세요

SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM
(SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY, B.PARENT_ITEM_ID, A.PRICE 
FROM ITEM_INFO A JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID) C
WHERE C.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL) 
ORDER BY C.ITEM_ID DESC;