SELECT DATE_FORMAT(CTE.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, CTE.PRODUCT_ID, CTE.USER_ID, CTE.SALES_AMOUNT
FROM
((SELECT SALES_DATE, PRODUCT_ID, SALES_AMOUNT, USER_ID
FROM ONLINE_SALE)
UNION ALL
(SELECT SALES_DATE, PRODUCT_ID, SALES_AMOUNT, NULL AS USER_ID
FROM OFFLINE_SALE)) AS CTE
WHERE YEAR(CTE.SALES_DATE) = 2022 AND MONTH(CTE.SALES_DATE) = 3
ORDER BY 1, 2, 3;