-- 코드를 입력하세요


WITH CTE AS (
    SELECT DISTINCT C1.CAR_ID, C1.CAR_TYPE, 
        FLOOR(((100- (SELECT C3.DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN C3 WHERE C3.CAR_TYPE = C1.CAR_TYPE AND C3.DURATION_TYPE = "30일 이상")) / 100 * C1.DAILY_FEE * 30)) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C1 LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY C2 ON C1.CAR_ID = C2.CAR_ID
    WHERE C1.CAR_TYPE IN ("세단", "SUV") AND
        NOT EXISTS (
        SELECT 1 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C4
        WHERE C1.CAR_ID = C4.CAR_ID AND
            (C4.START_DATE <= DATE('2022-11-30') AND C4.END_DATE >= DATE('2022-11-01'))
    )
)

SELECT CAR_ID, CAR_TYPE, FEE
FROM CTE
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC

# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR C1 LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY C2 ON C1.CAR_ID = C2.CAR_ID