-- 코드를 입력하세요
SELECT C.USER_ID, C.NICKNAME, CONCAT(C.CITY, " ", C.STREET_ADDRESS1, " ", C.STREET_ADDRESS2) AS "전체주소", 
CONCAT(SUBSTRING(C.TLNO, 1, 3), "-", SUBSTRING(C.TLNO, 4, 4), "-", SUBSTRING(C.TLNO, 8, 4)) AS "전화번호"
FROM USED_GOODS_USER C
WHERE C.USER_ID IN 
(SELECT DISTINCT A.WRITER_ID
FROM USED_GOODS_BOARD A
WHERE 
(SELECT COUNT(*) FROM USED_GOODS_BOARD B  WHERE WRITER_ID = A.WRITER_ID) >= 3)
ORDER BY C.USER_ID DESC;
