-- 코드를 입력하세요
SELECT ANIMAL_ID, O.ANIMAL_TYPE, NVL(O.NAME, I.NAME)
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O
USING (ANIMAL_ID) 
WHERE SEX_UPON_INTAKE LIKE 'Intact%' and SEX_UPON_OUTCOME NOT LIKE 'Intact%';
