-- 코드를 입력하세요
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, B.SCORE
FROM REST_INFO AS A JOIN (SELECT C.REST_ID, ROUND(AVG(C.REVIEW_SCORE), 2) AS SCORE
                          FROM REST_REVIEW AS C GROUP BY C.REST_ID) 
AS B ON B.REST_ID = A.REST_ID
WHERE A.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, A.FAVORITES DESC;