-- 코드를 작성해주세요
WITH RECURSIVE CTE AS(
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT A.ID, A.PARENT_ID, B.GEN+1 AS GEN
    FROM ECOLI_DATA A JOIN CTE B
    ON A.PARENT_ID = B.ID
)
SELECT COUNT(C.ID) AS COUNT, C.GEN AS GENERATION
FROM CTE C
WHERE C.ID NOT IN (SELECT DISTINCT E.PARENT_ID FROM ECOLI_DATA E WHERE PARENT_ID IS NOT NULL)
GROUP BY C.GEN
ORDER BY C.GEN
;