WITH RECURSIVE TMP AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, T.GEN+1
    FROM ECOLI_DATA E, TMP T
    WHERE E.PARENT_ID = T.ID
)

SELECT COUNT(*) AS COUNT, GEN AS GENERATION
FROM TMP T
WHERE (SELECT COUNT(*) FROM ECOLI_DATA E WHERE E.PARENT_ID = T.ID) = 0
GROUP BY GEN
ORDER BY 2