-- 코드를 입력하세요
WITH CTE AS (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(*) >= 2
)

SELECT A.ID, A.NAME, A.HOST_ID
FROM PLACES A JOIN CTE C ON A.HOST_ID = C.HOST_ID
ORDER BY 1;