-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT * PRICE) TOTAL_SALES
FROM FOOD_ORDER JOIN FOOD_PRODUCT
USING (PRODUCT_ID)
WHERE EXTRACT(YEAR FROM PRODUCE_DATE) = 2022 
    AND EXTRACT(MONTH FROM PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID

