SELECT HISTORY_ID,
    CASE WHEN (DURATION+1) < 7 THEN (DURATION+1) * DAILY_FEE
            WHEN (DURATION+1) < 30 THEN FLOOR((DURATION+1)* DAILY_FEE * 
                                    (100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                                     WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '7%')) / 100)
            WHEN (DURATION+1) < 90 THEN FLOOR((DURATION+1) * DAILY_FEE * 
                                    (100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                                     WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '30%')) / 100)
            ELSE FLOOR((DURATION+1) * DAILY_FEE * 
                (100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                     WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '90%')) / 100)
        END FEE     
FROM
(
SELECT HISTORY_ID, CAR_ID, (END_DATE - START_DATE) DURATION, DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
USING (CAR_ID)
WHERE A.CAR_TYPE = '트럭'
)
ORDER BY FEE DESC, HISTORY_ID DESC
