-- 코드를 입력하세요
SELECT HISTORY_ID,
FLOOR(CASE
WHEN DATEDIFF(END_DATE, START_DATE)+1 < 7 THEN DAILY_FEE
      
WHEN DATEDIFF(END_DATE, START_DATE)+1 < 30 THEN DAILY_FEE * 
(100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
 WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상')) / 100
      
WHEN DATEDIFF(END_DATE, START_DATE)+1 < 90 THEN DAILY_FEE * 
(100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
 WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상')) / 100
      
ELSE DAILY_FEE * 
(100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
 WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상')) / 100
END) * (DATEDIFF(END_DATE, START_DATE)+1) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A, (SELECT CAR_ID, DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR
                 WHERE CAR_TYPE = '트럭') B
WHERE A.CAR_ID = B.CAR_ID 
ORDER BY FEE DESC, HISTORY_ID DESC
