WITH MAIN AS (
    SELECT C2.HISTORY_ID, C1.DAILY_FEE, SUM(DATEDIFF(C2.END_DATE, C2.START_DATE)+1) AS TOTAL
    FROM CAR_RENTAL_COMPANY_CAR C1 INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY C2 ON C1.CAR_ID = C2.CAR_ID
    WHERE C1.CAR_TYPE = "트럭"
    GROUP BY C2.HISTORY_ID, C1.DAILY_FEE
)

SELECT M.HISTORY_ID, 
    FLOOR((100- 
           (SELECT 
                (CASE WHEN M.TOTAL >= 90 THEN 
                 (SELECT C3.DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN C3 WHERE C3.CAR_TYPE = "트럭" AND C3.DURATION_TYPE = "90일 이상")
                WHEN M.TOTAL >= 30 THEN 
                 (SELECT C3.DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN C3 WHERE C3.CAR_TYPE = "트럭" AND C3.DURATION_TYPE = "30일 이상")
                WHEN M.TOTAL >= 7 THEN
                 (SELECT C3.DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN C3 WHERE C3.CAR_TYPE = "트럭" AND C3.DURATION_TYPE = "7일 이상")
                ELSE 0
                END)
           )
    ) / 100 * M.DAILY_FEE * M.TOTAL) AS FEE
FROM MAIN M
ORDER BY FEE DESC, M.HISTORY_ID DESC
