-- 코드를 입력하세요
WITH RECURSIVE cte AS (
    SELECT 0 AS num
    UNION ALL
    SELECT num + 1
    FROM cte
    WHERE num < 23
) 
SELECT C.NUM, COUNT(HOUR(A.DATETIME))
FROM ANIMAL_OUTS A RIGHT OUTER JOIN CTE C
ON HOUR(A.DATETIME) = C.NUM
GROUP BY C.NUM