-- 코드를 작성해주세요
WITH FE AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, FE
WHERE D.SKILL_CODE & FE.CODE
ORDER BY 1;