-- 코드를 입력하세요
SELECT A.WRITER_ID AS USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM (SELECT WRITER_ID, PRICE
     FROM USED_GOODS_BOARD
     WHERE STATUS = 'DONE') A INNER JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
GROUP BY A.WRITER_ID, B.NICKNAME
HAVING (SUM(A.PRICE) >= 700000)
ORDER BY SUM(A.PRICE)