-- 코드를 작성해주세요
SELECT I2.ITEM_ID, I3.ITEM_NAME, I3.RARITY
FROM ITEM_INFO I1 JOIN ITEM_TREE I2 ON I1.ITEM_ID = I2.PARENT_ITEM_ID
JOIN ITEM_INFO I3 ON I2.ITEM_ID = I3.ITEM_ID
WHERE I1.RARITY = 'RARE'
ORDER BY 1 DESC;
