SELECT A.CATEGORY, A.PRICE AS MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A
WHERE A.CATEGORY IN ('과자', '국', '김치', '식용유') AND
A.PRICE = (SELECT MAX(B.PRICE) 
FROM FOOD_PRODUCT B WHERE B.CATEGORY = A.CATEGORY
GROUP BY CATEGORY)
ORDER BY 2 DESC