WITH FE AS (
    SELECT SUM(CODE) CODES, CATEGORY 
    FROM SKILLCODES
    GROUP BY CATEGORY
    HAVING CATEGORY = 'Front End'
), 
PY AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
), 
C AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
),    
TMP AS (
    SELECT 
    CASE
        WHEN D.SKILL_CODE & FE.CODES AND D.SKILL_CODE & PY.CODE THEN 'A'
        WHEN D.SKILL_CODE & C.CODE THEN 'B'
        WHEN D.SKILL_CODE & FE.CODES THEN 'C'
        ELSE NULL
    END AS GRADE,
    D.ID, D.EMAIL
    FROM DEVELOPERS D, FE, PY, C
)



SELECT GRADE, ID, EMAIL
FROM TMP
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;
    

    
    
    
    
    