WITH PYTHON AS (
    SELECT CODE FROM SKILLCODES WHERE NAME = "Python"
), FRONT AS (
    SELECT SUM(CODE) AS CODE_SUM FROM SKILLCODES WHERE CATEGORY = "Front End"
), CS AS (
    SELECT CODE FROM SKILLCODES WHERE NAME = "C#"
), GRADE AS (
    SELECT (CASE WHEN (D.SKILL_CODE & P.CODE) = P.CODE AND (D.SKILL_CODE & F.CODE_SUM) != 0 THEN 'A'
        WHEN (D.SKILL_CODE & C.CODE) = C.CODE THEN 'B'
        WHEN (D.SKILL_CODE & F.CODE_SUM) != 0 THEN 'C'
        ELSE NULL
    END) AS GRADE, D.ID, D.EMAIL
    FROM DEVELOPERS D, PYTHON P, FRONT F, CS C
)

SELECT GRADE, ID, EMAIL
FROM GRADE
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID